(function(g){var window=this;'use strict';var yJE=function(t,F,I){g.w(function(v){t.N=g.Bw(F,I);g.le(v)})},RU=function(t){t.isActive()||t.start()},Uzs=function(t,F){return F?t.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Yg_=function(t){return g.pD(t)||t.Y("web_enable_caption_language_preference_stickiness")},lA3=function(t,F){var I=new g.zs;
I.languageCode=t.languageCode;I.languageName=t.languageName;I.name=t.name;I.displayName=t.displayName;I.kind=t.kind;I.isDefault=!1;I.N=t.N;I.isTranslateable=t.isTranslateable;I.vssId=t.vssId;I.url=t.url;I.translationLanguage=F;t.xtags&&(I.xtags=t.xtags);t.captionId&&(I.captionId=t.captionId);return I},Wqs=function(t,F){var I,v,H;
return g.w(function(S){if(S.N==1)return I=t+"|"+F,g.a(S,g.DE(),2);if(S.N!=3){v=S.S;if(!v)throw g.y1("gct");return g.a(S,g.nI(v),3)}H=S.S;return S.return(H.get("captions",I))})},X54=function(t,F,I){Wqs(t,F).then(function(v){v&&I(v.trackData,new g.zs(v.metadata))})},VzE=function(t){if(!ezO.test(t))throw Error("'"+t+"' is not a valid hex color");
t.length==4&&(t=t.replace(dzI,"#$1$1$2$2$3$3"));t=t.toLowerCase();t=parseInt(t.slice(1),16);return[t>>16,t>>8&255,t&255]},p5O=function(){var t=void 0;
t=t===void 0?{}:t;var F="suggest_correction"in g.z0F?g.z0F.suggest_correction:"Edit caption";F=F||"";var I={},v;for(v in t){I={BM:I.BM};I.BM=v;var H=function(S){return function(){return String(t[S.BM])}}(I);
F=F.replace(new RegExp("\\$\\{"+I.BM+"\\}","gi"),H);F=F.replace(new RegExp("\\$"+I.BM,"gi"),H)}return F},B_I=function(){return g.ku("yt-player-caption-display-settings")},nc=function(){this.segments=[]},$z0=function(t,F){var I=g.bs(t.segments,F);
I>=0||I<0&&(-I-1)%2===1||(I=-I-1,I>0&&F-t.segments[I-1]===1&&I<t.segments.length&&t.segments[I]-F===1?(g.ls(t.segments,I),g.ls(t.segments,I-1)):I>0&&F-t.segments[I-1]===1?t.segments[I-1]=F:I<t.segments.length&&t.segments[I]-F===1?t.segments[I]=F:(g.PG(t.segments,I,0,F),g.PG(t.segments,I+1,0,F)))},mzZ=function(t,F,I,v,H,S){g.c.call(this);
this.policy=t;this.player=F;this.kP=I;this.j=v;this.C=H;this.U=S;this.J=new nc;this.V=-1;this.S=this.T=this.N=null;this.e7=0;this.B=new g.FW(this.IN,1E3,this);this.events=new g.BL(this);g.P(this,this.B);g.P(this,this.events);this.events.W(F,"SEEK_COMPLETE",this.XG);this.XG();this.IN()},aAO=function(t){return t.N&&t.N.V?t.N.V+t.player.Ki()<t.player.getCurrentTime():!1},w5E=function(t,F){if(t.policy.I4&&t.player.KD()){var I=g.My(F,t.policy,{});
I.set("pot",t.player.KD());I=I.uY()}else I=g.My(F,t.policy,{}).uY();var v={format:"RAW",withCredentials:!0};if(t.policy.bz){v.method="POST";var H=F.J;H&&Object.keys(H).length>0?v.postBody=g.qr(H,g.cL):v.postBody=(0,g.x3)([120,0])}t.C&&(v.responseType="arraybuffer");var S=++t.e7,f=(0,g.ef)();t.S=g.w9(I,v,3,100,-1,function(Q){Q.errorCode==="net.timeout"&&t.player.Nf("capnt",{rn:S++})}).then(function(Q){if(t.policy.wb&&S%100===1){var R=(0,g.ef)();
t.player.Nf("caprsp",{rn:S,ms:R-f,kb:(Q.xhr.responseText.length/1024).toFixed()})}a:{Q=Q.xhr;t.Et();if(t.T){var n=!(t.C?Q.response:Q.responseText)||Q.status>=400;if(R=g.Met(Q)){Q=g.My(t.T,t.policy,{});t.T.DO(Q,R);w5E(t,t.T);break a}if(n)t.player.Nf("capfail",{status:Q.status});else{var N;g.jw("fcb_r",(0,g.ef)(),((N=t.player.getVideoData())==null?void 0:N.kP)||"");N=t.T.Ut[0];R=N.P3;t.j!=null&&t.V!==R&&(t.C?t.j(Q.response,(N.startTime+t.player.Ki())*1E3):t.j(Q.responseText,(N.startTime+t.player.Ki())*
1E3),t.V=R)}}t.T=null;t.S=null}}).jk(function(Q){t.T=null;
t.S=null;var R;t.player.Nf("capfail",{rn:S,status:(R=Q.xhr)==null?void 0:R.status})});
t.T=F;$z0(t.J,t.T.Ut[0].P3)},s2=function(t,F){g.XN.call(this,F);
this.N=t;this.Z=F;this.J=null;this.V=!1;this.logger=new g.eb("caps");this.B=g.qw0(this.Z,this.N)},AJI=function(t,F){var I=[],v;
for(v in t.N.N)if(t.N.N.hasOwnProperty(v)){var H=t.N.N[v];if(g.d$(H,F||null)){var S=H.info.id,f=S,Q="."+S,R="",n="";if(H=H.info.captionTrack)S=H.languageCode,f=H.displayName,Q=H.vssId,R=H.kind,n=H.id;else{H=S;var N=g.TFy.get(H);N==null&&(N=rJZ[H]||rJZ[H.replace(/-/g,"_")],g.TFy.set(H,N));H=N;f=H||f}I.push(new g.zs({id:v,languageCode:S,languageName:f,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:Q,kind:R,captionId:n}))}}return I},kG4=function(t,F){return F!=null&&F in t.N.N?t.N.N[F]:null},
hz_=function(t,F,I){var v=[],H;
for(H in t.N.N)if(t.N.N.hasOwnProperty(H)){var S=t.N.N[H];if(g.d$(S,I||null)){var f=S.info.captionTrack;f&&f.languageCode===F&&v.push(S)}}return v.length?v[0]:null},NW=function(t,F,I,v,H,S,f,Q,R,n){var N=n.isInline()&&!0,M={};
Object.assign(M,F);Object.assign(M,t.params);Object.assign(M,I);var E={};Object.assign(E,F.IK);t.params.IK&&Object.assign(E,t.params.IK);Object.assign(E,I.IK);N&&(M.windowOpacity=.6,E.backgroundOpacity=0);M.IK=E;var O=M.Wv===1,T=[{D:"span",X:"captions-text",G:{style:"word-wrap: normal; display: block;"}}],W,e,B;(Q=Q.Ah("caption_edit_on_hover")&&((W=n.getVideoData().getPlayerResponse())==null?void 0:(e=W.captions)==null?void 0:(B=e.playerCaptionsTracklistRenderer)==null?void 0:B.openTranscriptCommand))&&
T.unshift({D:"button",X:"caption-edit",G:{tabindex:"0","aria-label":p5O()},L:[{D:"svg",G:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},L:[{D:"path",G:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.b.call(this,{D:"div",X:"caption-window",G:{id:"caption-window-"+t.id,dir:O?"rtl":"ltr",tabindex:"0",lang:M.lang},L:T});var p=
this;this.V=[];this.D3=!1;this.S=t;this.bz=this.pF=null;this.TN=S;this.AN=f;this.B=null;this.maxWidth=S*.96;this.maxHeight=f*.96;this.N=M;this.Li=I;this.e7=F;this.J=this.F4("captions-text");this.Pb=this.J.style.getPropertyValue("box-decoration-break")!==""||this.J.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.X4=cJG(v,H,S,f);this.lk=R;Q&&(this.C=this.F4("caption-edit"),this.W(this.C,"click",function(){p.lk()}));
this.type=0;this.iz=this.X4*PLy(E);this.IF=N;t=new g.hH(this.element,!0);g.P(this,t);t.subscribe("dragstart",this.Sg,this);t.subscribe("dragmove",this.eg,this);t.subscribe("dragend",this.NZ,this);this.KF=this.zY=this.Mf=this.LF=0;t="";this.N.windowOpacity&&(t=VzE(this.N.windowColor),t="rgba("+t[0]+","+t[1]+","+t[2]+","+this.N.windowOpacity+")");F={"background-color":t,display:this.N.isVisible===!1?"none":"","text-align":JJT[this.N.textAlign]};this.Pb&&(F["border-radius"]=t?this.iz/8+"px":"");(this.T=
this.S.params.Wv===2||this.S.params.Wv===3)&&Kqy(this,this.element);g.gN(this.element,F);if(N){var r;(r=this.element.parentElement)==null||r.style.setProperty("--caption-window-color",t)}switch(this.N.Ij){case 0:case 1:case 2:g.nq(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.nq(this.element,"ytp-caption-window-bottom")}},Kqy=function(t,F){var I="vertical-rl";
t.N.Tl===1&&(I="vertical-lr");g.yD&&(I=I==="vertical-lr"?"tb-lr":"tb-rl");g.gN(F,"-o-writing-mode",I);g.gN(F,"-webkit-writing-mode",I);g.gN(F,"writing-mode",I);g.gN(F,"text-orientation","upright");g.nq(F,"ytp-vertical-caption");t.S.params.Wv===3&&(g.gN(F,"text-orientation",""),g.gN(F,"transform","rotate(180deg)"))},PLy=function(t){var F=1+.25*(t.fontSizeIncrement||0);
if(t.offset===0||t.offset===2)F*=.8;return F},br3=function(t,F){var I={},v=F.background?F.background:t.N.IK.background;
if(F.backgroundOpacity!=null||F.background){var H=F.backgroundOpacity!=null?F.backgroundOpacity:t.N.IK.backgroundOpacity;v=VzE(v);I.background="rgba("+v[0]+","+v[1]+","+v[2]+","+H+")";t.Pb&&(I["box-decoration-break"]="clone",I["border-radius"]=t.iz/8+"px")}if(F.fontSizeIncrement!=null||F.offset!=null)I["font-size"]=t.X4*PLy(F)+"px";v=1;H=F.color||t.N.IK.color;if(F.color||F.textOpacity!=null)H=VzE(H),v=F.textOpacity==null?t.N.IK.textOpacity:F.textOpacity,H="rgba("+H[0]+","+H[1]+","+H[2]+","+v+")",
I.color=H,I.fill=H;var S=F.charEdgeStyle;S===0&&(S=void 0);if(S){H="rgba(34, 34, 34, "+v+")";var f="rgba(204, 204, 204, "+v+")";F.y6&&(f=H=F.y6);var Q=t.X4/16/2,R=Math.max(Q,1),n=Math.max(2*Q,1),N=Math.max(3*Q,1),M=Math.max(5*Q,1);v=[];switch(S){case 4:for(;N<=M;N+=Q)v.push(n+"px "+n+"px "+N+"px "+H);break;case 1:n=window.devicePixelRatio>=2?.5:1;for(S=R;S<=N;S+=n)v.push(S+"px "+S+"px "+H);break;case 2:v.push(R+"px "+R+"px "+f);v.push("-"+R+"px -"+R+"px "+H);break;case 3:for(N=0;N<5;N++)v.push("0 0 "+
n+"px "+H)}I["text-shadow"]=v.join(", ")}H="";switch(F.fontFamily){case 1:H='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:H='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:H='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:H='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:H='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:H=g.Lk()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:H='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}H&&(I["font-family"]=H);H=F.offset;H==null&&(H=t.N.IK.offset);switch(H){case 0:I["vertical-align"]="sub";break;case 2:I["vertical-align"]="super"}F.fontFamily===7&&(I["font-variant"]="small-caps");F.bold&&(I["font-weight"]="bold");F.italic&&(I["font-style"]="italic");F.underline&&(I["text-decoration"]=
"underline");F.hA&&(I.visibility="hidden");F.c_===1&&t.T&&(I["text-combine-upright"]="all",I["text-orientation"]="mixed",H=g.aA||g.OC,t.S.params.Wv===3?I.transform=H?"rotate(90deg)":"rotate(180deg)":H&&(I.transform="rotate(-90deg)"));if(F.textEmphasis===1||F.textEmphasis===2||F.textEmphasis===3||F.textEmphasis===4||F.textEmphasis===5)if(g.aA)I["font-weight"]="bold";else switch(I["text-emphasis-style"]="filled circle",I["text-emphasis-color"]="currentcolor",I["webkit-text-emphasis"]="filled circle",
F.textEmphasis){case 4:case 3:I["text-emphasis-position"]="under left";I["webkit-text-emphasis-position"]="under left";break;case 5:case 2:I["text-emphasis-position"]="over right",I["webkit-text-emphasis-position"]="over right"}return I},oU=function(t){t=t.split("px");
return t.length>0?(t=Number(t[0]))?t:0:0},CLF=function(t){t.B=g.or("SPAN");
g.gN(t.B,{display:"block"});g.nq(t.B,"caption-visual-line");t.J.appendChild(t.B)},gCI=function(t,F){var I=g.or("SPAN");
g.gN(I,{display:"inline-block","white-space":"pre-wrap"});g.gN(I,br3(t,F));I.classList.add("ytp-caption-segment");t.B.appendChild(I);I.previousElementSibling&&(g.gN(I.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.gN(I,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return I},xzy=function(t,F,I){t.D3=t.D3||!!I;
var v={};Object.assign(v,t.N.IK);Object.assign(v,I||F.N);Object.assign(v,t.Li.IK);(I=!t.B)&&CLF(t);for(var H=t.pF&&t.bz&&g.oy(v,t.bz)?t.pF:gCI(t,v),S=typeof F.text==="string",f=S?F.text.split("\n"):[F.text],Q=0;Q<f.length;Q++){var R=Q>0||!F.append,n=f[Q];R&&!I?(CLF(t),H=gCI(t,v)):R&&I&&(I=!1);n&&(H.appendChild(S?g.MP(n):n),S||n.tagName!=="RUBY"||n.childElementCount!==4||g.aA||!g.zf(n.children[2],"text-emphasis")||(R=t.T?"padding-right":"padding-top",g.zf(n.children[2],"text-emphasis-position")&&(R=
t.T?"padding-left":"padding-bottom"),g.Rr?g.gN(H,R,"1em"):g.gN(H,R,"0.5em")))}t.bz=v;t.pF=H;t.V.push(F)},cJG=function(t,F,I,v){var H=F/360*16;
F>=t&&(t=640,v>I*1.3&&(t=480),H=I/t*16);return H},uEO=function(){this.T=this.time=this.mode=this.S=0;
this.J=new zzI(this);this.C=new zzI(this);this.N=[];this.clear()},ZrE=function(t,F,I){if(t===255&&F===255||!t&&!F)return{NQ:t,
xu:F,result:0};t=LqI[t];F=LqI[F];if(t&128){var v;if(v=!(F&128))v=F,v=I.Yd()&&I.xu===v;if(v)return{NQ:t,xu:F,result:1}}else if(F&128&&1<=t&&t<=31)return{NQ:t,xu:F,result:2};return{NQ:t,xu:F,result:3}},qgO=function(t,F,I,v){F===255&&I===255||!F&&!I?(++t.T===45&&t.reset(),t.J.S.clear(),t.C.S.clear()):(t.T=0,DzT(t.J,F,I,v))},iPE=function(t,F){t.N.sort(function(H,S){var f=H.time-S.time;
return f===0?H.order-S.order:f});
for(var I=g.l(t.N),v=I.next();!v.done;v=I.next())v=v.value,t.time=v.time,v.type===0?qgO(t,v.Oq,v.Uq,F):v.type===1&&t.S&496&&DzT(t.C,v.Oq,v.Uq,F);t.N.length=0},MW=function(){this.type=0},E2=function(){this.state=this.xu=this.NQ=0},t7E=function(){this.timestamp=this.N=0},O2=function(t){this.C=t;
this.T=[];this.N=this.S=this.row=0;this.style=new MW;for(t=this.J=0;t<=15;t++){this.T[t]=[];for(var F=0;F<=32;F++)this.T[t][F]=new t7E}},TA=function(t,F){if(t.style.type===3){for(var I=0,v=0,H=t.C.time+0,S="",f="",Q=H,R=1;R<=15;++R){for(var n=!1,N=v?v:1;N<=32;++N){var M=t.T[R][N];
if(M.N!==0){I===0&&(I=R,v=N);n=String.fromCharCode(M.N);var E=M.timestamp;E<H&&(H=E);M.timestamp=Q;f&&(S+=f,f="");S+=n;n=!0}if((M.N===0||N===32)&&n){f="\n";break}else if(v&&!n)break}if(I&&!n)break}S&&F.J(I,v,H,Q,S)}else for(v=I=0,S=H=t.C.time+0,f=1;f<=15;++f)for(Q="",R=1;R<=32;++R)if(N=t.T[f][R],M=N.N,M!==0&&(I===0&&(I=f,v=R),n=String.fromCharCode(M),E=N.timestamp,E<=H&&(H=E),Q+=n,N.reset()),R===32||M===0)Q&&F.J(I,v,H,S,Q),H=S,Q="",v=I=0},Sm3=function(t,F){switch(t){case 0:return Fr3[(F&127)-32];
case 1:return IK0[F&15];case 2:return vdZ[F&31];case 3:return HPZ[F&31]}return 0},yI=function(t){return t.T[t.row][t.S]},U2=function(t,F,I){F>=2&&t.S>1&&(--t.S,yI(t).N=0);
var v=yI(t);v.timestamp=t.C.time+0;v.N=Sm3(F,I);t.S<32&&t.S++},jJG=function(t,F,I,v){for(var H=0;H<v;H++)for(var S=0;S<=32;S++){var f=t.T[F+H][S],Q=t.T[I+H][S];
f.N=Q.N;f.timestamp=Q.timestamp}},YN=function(t,F,I){for(var v=0;v<I;v++)for(var H=0;H<=32;H++)t.T[F+v][H].reset()},fKF=function(t){t.row=t.N>0?t.N:1;
t.S=1;YN(t,0,15)},GQZ=function(t){this.T=t;
this.C=0;this.style=new MW;this.V=new O2(this.T);this.B=new O2(this.T);this.text=new O2(this.T);this.S=this.V;this.J=this.B;this.N=this.S},QJO=function(t,F,I){var v=t.S,H=!1;
switch(t.style.get()){case 4:case 1:case 2:t.style.get()===4&&v.N>0||(TA(v,I),fKF(t.S),fKF(t.J),v.row=15,v.N=F,H=!0)}t.style.set(3);t.N=v;t.N.style=t.style;t.T.mode=1<<v.J;H?v.S=1:v.N!==F&&(v.N>F?(TA(v,I),YN(v,v.row-v.N,F)):v.row<F&&(F=v.N),v.N=F)},RaE=function(t){t.style.set(1);
t.N=t.J;t.N.N=0;t.N.style=t.style;t.T.mode=1<<t.N.J},nd3=function(t){t.style.set(4);
t.N=t.text;t.N.style=t.style;t.T.mode=1<<t.N.J},zzI=function(t){this.N=t;
this.C=0;this.T=new GQZ(this.N);this.V=new GQZ(this.N);this.S=new E2;this.J=this.T},DzT=function(t,F,I,v){t.S.update();
F=ZrE(F,I,t.S);switch(F.result){case 0:return;case 1:case 2:return}var H=F.NQ;I=F.xu;if(32<=H||!H)t.N.mode&t.N.S&&(F=H,F&128&&(F=127),I&128&&(I=127),t=t.J.N,F&96&&U2(t,0,F),I&96&&U2(t,0,I),F!==0&&I!==0&&t.style.type===3&&TA(t,v));else if(H&16)a:if(!t.S.matches(H,I)&&(F=t.S,F.NQ=H,F.xu=I,F.state=2,F=H&8?t.V:t.T,t.J=F,t.N.mode=1<<(t.C<<2)+(F.C<<1)+(F.style.type===4?1:0),(t.N.mode|1<<(t.C<<2)+(F.C<<1)+(F.style.type!==4?1:0))&t.N.S))if(I&64){v=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(H&7)<<1|I>>5&1];
t=I&16?((I&14)>>1)*4:0;I=F.N;switch(F.style.get()){case 4:v=I.row;break;case 3:if(v!==I.row){if(v<I.N&&(v=I.N,v===I.row))break;var S=1+I.row-I.N,f=1+v-I.N;jJG(I,f,S,I.N);F=S;H=I.N;f<S?(S=f+H-S,S>0&&(F+=S,H-=S)):(S=S+H-f,S>0&&(H-=S));YN(I,F,H)}}I.row=v;I.S=t+1}else switch(H&7){case 1:switch(I&112){case 32:U2(F.N,0,32);break a;case 48:I===57?(v=F.N,yI(v).N=0,v.S<32&&v.S++):U2(F.N,1,I&15)}break;case 2:I&32&&U2(F.N,2,I&31);break;case 3:I&32&&U2(F.N,3,I&31);break;case 4:case 5:if(32<=I&&I<=47)switch(I){case 32:RaE(F);
break;case 33:v=F.N;v.S>1&&(--v.S,yI(v).N=0);break;case 36:v=F.N;F=yI(v);for(t=0;t<=15;t++)for(I=0;I<=32;I++)if(v.T[t][I]===F){for(;I<=32;I++)v.T[t][I].reset();break}break;case 37:QJO(F,2,v);break;case 38:QJO(F,3,v);break;case 39:QJO(F,4,v);break;case 40:U2(F.N,0,32);break;case 41:F.style.set(2);F.N=F.S;F.N.N=0;F.N.style=F.style;F.T.mode=1<<F.N.J;break;case 42:v=F.text;v.N=15;v.style.set(4);fKF(v);nd3(F);break;case 43:nd3(F);break;case 44:t=F.S;switch(F.style.get()){case 1:case 2:case 3:TA(t,v)}YN(t,
0,15);break;case 45:b:{t=F.N;switch(F.style.get()){default:case 2:case 1:break b;case 4:if(t.row<15){++t.row;t.S=1;break b}break;case 3:}t.N<2&&(t.N=2,t.row<t.N&&(t.row=t.N));F=t.row-t.N+1;TA(t,v);jJG(t,F,F+1,t.N-1);YN(t,t.row,1)}break;case 46:YN(F.J,0,15);break;case 47:TA(F.S,v),F.J.updateTime(F.T.time+0),v=F.J,F.J=F.S,F.S=v,RaE(F)}break;case 7:switch(I){case 33:case 34:case 35:v=F.N,(v.S+=I&3)>32&&(v.S=32)}}},sJ4=function(){},l0=function(t,F,I,v,H,S,f){S=S===void 0?!1:S;
f=f===void 0?null:f;g.DX.call(this,t,t+F,{priority:I,namespace:"captions"});this.windowId=v;this.text=H;this.append=S;this.N=f},odG=function(t,F,I,v,H,S,f){var Q=S[0],R=f[Q.getAttribute("p")];
if(R.dK===1){var n=S[1],N=S[2];S=S[3];Q.getAttribute("t");n.getAttribute("t");N.getAttribute("t");S.getAttribute("t");Q.getAttribute("p");n.getAttribute("p");S.getAttribute("p");f=f[N.getAttribute("p")];Q=NEy(Q.textContent,n.textContent,N.textContent,S.textContent,f);return new l0(t,F,H,I,Q,v,R)}switch(R.dK){case 9:case 10:R.textEmphasis=1;break;case 11:R.textEmphasis=2;break;case 12:R.textEmphasis=3;break;case 13:R.textEmphasis=4;break;case 14:R.textEmphasis=5}return new l0(t,F,H,I,Q.textContent||
"",v,R)},NEy=function(t,F,I,v,H){var S=g.Lk(),f=S?g.or("DIV"):g.or("RUBY"),Q=g.or("SPAN");
Q.textContent=t;f.appendChild(Q);t=S?g.or("DIV"):g.or("RP");t.textContent=F;f.appendChild(t);F=S?g.or("DIV"):g.or("RT");F.textContent=I;f.appendChild(F);I=H.dK;if(I===10||I===11||I===12||I===13||I===14)if(g.gN(F,"text-emphasis-style","filled circle"),g.gN(F,"text-emphasis-color","currentcolor"),g.gN(F,"webkit-text-emphasis","filled circle"),H.dK===11||H.dK===13)g.gN(F,"webkit-text-emphasis-position","under left"),g.gN(F,"text-emphasis-position","under left");I=!0;if(H.dK===4||H.dK===7||H.dK===12||
H.dK===14)g.gN(f,"ruby-position","over"),g.gN(f,"-webkit-ruby-position","before");else if(H.dK===5||H.dK===6||H.dK===11||H.dK===13)g.gN(f,"ruby-position","under"),g.gN(f,"-webkit-ruby-position","after"),I=!1;H=S?g.or("DIV"):g.or("RP");H.textContent=v;f.appendChild(H);S&&(v=I,g.gN(f,{display:"inline-block",position:"relative"}),S=f.firstElementChild.nextElementSibling,g.gN(S,"display","none"),S=S.nextElementSibling,g.gN(S,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.gN(f.lastElementChild,"display","none"),v?(g.gN(f,"padding-top","0.6em"),g.gN(S,"top","0")):(g.gN(f,"padding-bottom","0.6em"),g.gN(S,"bottom","0")));return f},Wx=function(){g.c.apply(this,arguments)},X_=function(t,F,I,v,H){g.DX.call(this,t,t+F,{priority:I,
namespace:"captions"});this.id=v;this.params=H;this.N=[]},M73=function(t){var F="_"+e3++;
return new X_(0,0x8000000000000,0,F,t)},dB=function(t){Wx.call(this);
this.J=t;this.pens={};this.j={};this.U={};this.C="_"+e3++;this.B={};this.S=this.N=null;this.V=!0},VI=function(t,F){t=t.getAttribute(F);
if(t!=null)return Number(t)},pc=function(t,F){t=t.getAttribute(F);
if(t!=null)return t==="1"},Bx=function(t,F){t=VI(t,F);
return t!==void 0?t:null},m$=function(t,F){t=t.getAttribute(F);
if(t!=null)return $N.test(t),t},EdI=function(t,F){var I={},v=F.getAttribute("ws");
Object.assign(I,v?t.U[v]:t.J);t=Bx(F,"mh");t!=null&&(I.Iq=t);t=Bx(F,"ju");t!=null&&(I.textAlign=t);t=Bx(F,"pd");t!=null&&(I.Wv=t);t=Bx(F,"sd");t!=null&&(I.Tl=t);t=m$(F,"wfc");t!=null&&(I.windowColor=t);F=VI(F,"wfo");F!==void 0&&(I.windowOpacity=F/255);return I},OP0=function(t,F){var I={},v=F.getAttribute("wp");
v&&Object.assign(I,t.j[v]);t=Bx(F,"ap");t!=null&&(I.Ij=t);t=VI(F,"cc");t!=null&&(I.Q7=t);t=VI(F,"ah");t!=null&&(I.bb=t);t=VI(F,"rc");t!=null&&(I.Z8=t);F=VI(F,"av");F!=null&&(I.Dv=F);return I},TE0=function(t,F,I,v){var H={};
Object.assign(H,OP0(t,F));Object.assign(H,EdI(t,F));v?g.oy(H,t.J)?(v=t.C,H=t.J):v="_"+e3++:v=F.getAttribute("id")||"_"+e3++;t=VI(F,"t")+I;F=VI(F,"d")||0x8000000000000;if(H.Wv===2||H.Wv===3)I=H.Z8,H.Z8=H.Q7,H.Q7=I;return new X_(t,F,0,v,H)},aU=function(t){Wx.call(this);
this.V=t;this.N=new Map;this.J=new Map;this.C=new Map;this.S=new Map},wB=function(t){t=g.J$(Math.round(t),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-t.length)+t},yhI=function(t,F,I,v,H){v===0&&(v=0x8000000000000);
var S={};F.wpWinPosId&&Object.assign(S,t.J.get(F.wpWinPosId));F.wsWinStyleId&&Object.assign(S,t.C.get(F.wsWinStyleId));t=F.rcRowCount;t!==void 0&&(S.Z8=t);F=F.ccColCount;F!==void 0&&(S.Q7=F);if(S.Wv===2||S.Wv===3)F=S.Z8,S.Z8=S.Q7,S.Q7=F;return new X_(I,v,0,H,S)},rB=function(t,F,I){g.XN.call(this,t);
this.videoData=F;this.audioTrack=I;this.C=F.b7},AO=function(t,F,I,v,H,S,f,Q,R,n){NW.call(this,t,F,I,v,H,S,f,Q,R,n);
this.type=1},kN=function(t,F,I){this.trackData=t;
this.V=I;this.version=this.C=this.T=this.byteOffset=0;this.S=[];this.N=new DataView(this.trackData)},hO=function(t){var F=t.byteOffset;
t.byteOffset+=1;return t.N.getUint8(F)},cx=function(t){var F=t.byteOffset;
t.byteOffset+=4;return t.N.getUint32(F)},Px=function(t,F){Wx.call(this);
this.S=t;this.J=F;this.track=this.J.languageName==="CC3"?4:0;this.N=new uEO;this.N.S=1<<this.track},YmI=function(t){if(typeof t==="string")return!1;
t=new kN(t,8,0);return UVI(t)},UVI=function(t){if(!(t.byteOffset<t.N.byteLength)||cx(t)!==1380139777)return!1;
t.version=hO(t);if(t.version>1)return!1;hO(t);hO(t);hO(t);return!0},JO=function(t,F,I,v,H,S,f,Q,R,n){NW.call(this,t,F,I,v,H,S,f,Q,R,n);
var N=this;this.type=2;this.TY=[];this.kP=this.U=this.Z3=0;this.Jh=NaN;this.ea=0;this.a7=null;this.Sa=new g.FW(this.yK,433,this);this.C&&(n.createClientVe(this.C,this,167342),this.W(this.C,"click",function(){n.logClick(N.C)}),t=new g.hH(this.element,!0),g.P(this,t),t.subscribe("hoverstart",function(){n.logVisibility(N.C,!0)},this));
g.nq(this.element,"ytp-caption-window-rollup");g.P(this,this.Sa);g.gN(this.element,"overflow","hidden")},lKy=function(t,F){if(!F)return"";
t.T&&t.S.params.Tl!==1&&(F*=-1);return"translate"+(t.T?"X":"Y")+"("+F+"px)"},Wr4=function(t){t.TY=Array.from(t.element.getElementsByClassName("caption-visual-line"));
for(var F=t.S.params.Z8,I=0,v=0,H=t.TY.length-1;I<F&&H>-1;){var S=t.TY[H];v+=t.T?S.offsetWidth:S.offsetHeight;I++;H--}t.U=v;F=Math;I=F.max;isNaN(t.Jh)&&((v=t.N.Q7)?(H=g.or("SPAN"),g.Yb(H,"\u2013".repeat(v)),g.gN(H,br3(t,t.N.IK)),t.J.appendChild(H),t.Jh=H.offsetWidth,t.J.removeChild(H)):t.Jh=0);v=t.J;t.kP=I.call(F,t.Jh,t.ea,(t.T?v.offsetHeight:v.offsetWidth)+1)},XlO=function(t,F){Wr4(t);
var I=t.TY.reduce(function(S,f){return(t.T?f.offsetWidth:f.offsetHeight)+S},0);
I=t.U-I;if(I!==t.Z3){var v=I>0&&t.Z3===0,H=I<t.Z3;F||isNaN(I)||v||!H||(g.nq(t.element,"ytp-rollup-mode"),t.W(t.element,"transitionend",t.yK));g.gN(t.J,"transform",lKy(t,I));t.Z3=I}Wr4(t)},eaE=function(t,F,I,v){var H=this;
this.Z=t;this.T=F;this.logger=I;this.o7=v;this.Fe=[];this.V1=[];this.N=null;this.rH={DoP:function(){return H.N},
lM:function(){return H.Fe}};
t=g.f7(this.Z.K().experiments,"html5_override_micro_discontinuities_threshold_ms");this.S=t>0?t:10},V7E=function(t,F){t.N=function(I,v){if(I.info.J){var H=I;
if(t.V1.length>0){for(H=t.V1.shift();t.V1.length>0;)H=g.BK(H,t.V1.shift());H=g.BK(H,I)}if(H){I=H;try{var S=g.$6(I)*1E3}catch(n){S=I.info.startTime*1E3}try{var f=g.jvc(I)*1E3}catch(n){f=I.info.duration*1E3}if(S<0||f<0)S<0&&(S=I.info.startTime*1E3),f<0&&(f=I.info.duration*1E3);I.info.startTime=S/1E3;I.info.C=S/1E3;I.info.duration=f/1E3;I.info.j=f/1E3;S=t.lG(H);f=S.P3;S={formatId:S.formatId,startTimeMs:S.startTimeMs,durationMs:S.durationMs,ek:f,N3:f};f=dVE(t.Fe,S.startTimeMs);var Q=(I=f>=0?t.Fe[f]:null)?
I.startTimeMs+I.durationMs:0,R=S.startTimeMs+S.durationMs;!I||S.startTimeMs-Q>t.S?t.Fe.splice(f+1,0,S):(I.durationMs=Math.max(Q,R)-I.startTimeMs,I.N3=Math.max(I.N3,S.N3));v(t.Fe);S=g.pn(H);v=t.T;S=S.buffer.slice(S.byteOffset,S.byteLength+S.byteOffset);H=H.info.C;v.V?v.J==null?g.dl(v.logger,350058965,"Null loaded track meta data at captions data received"):F.fz(S,v.J,H*1E3):g.dl(v.logger,350058965,"Null Representation at captions data received")}else g.dl(t.logger,350058965,"Empty slice")}else t.V1.push(I)};
t.Z.addEventListener("sabrCaptionsDataLoaded",t.N)},dVE=function(t,F){t=g.bs(t,{startTimeMs:F},function(I,v){return I.startTimeMs-v.startTimeMs});
return t>=0?t:-t-2},Kc=function(t,F){g.XN.call(this,F);
this.N=t;this.Z=F;this.logger=new g.eb("caps");this.J=this.V=null;this.B=new eaE(this.Z,this,this.logger,this.N.o7)},plF=function(t,F){var I=[],v;
for(v in t.N.N)if(t.N.N.hasOwnProperty(v)){var H=t.N.N[v];if(g.d$(H,F||null)){var S=H.info.id,f=S,Q="."+S,R="",n="";if(H=H.info.captionTrack)S=H.languageCode,f=H.displayName,Q=H.vssId,R=H.kind,n=H.id;I.push(new g.zs({id:v,languageCode:S,languageName:f,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:Q,kind:R,captionId:n}))}}return I},BEZ=function(t,F,I){var v=[],H;
for(H in t.N.N)if(t.N.N.hasOwnProperty(H)){var S=t.N.N[H];if(g.d$(S,I||null)){var f=S.info.captionTrack;f&&f.languageCode===F&&v.push(S)}}return v.length?v[0]:null},$V3=function(t,F){if(!g.f3K(t)||t.N!=null&&g.qw0(F,t.N)&&t.N.N.rawcc!=null)return!1;
F=!!t.N&&t.N.isManifestless&&Object.values(t.N.N).some(function(I){return g.d$(I,"386")});
t=!!t.N&&!t.N.isManifestless&&g.yXc(t.N);return F||t},mVE=function(){Wx.call(this)},wl3=function(t){var F=aKE.length;
if(t.byteLength<F)return!1;t=new Uint8Array(t,0,F);for(var I=0;I<F;I++)if(aKE[I]!==t[I])return!1;return!0},rh3=function(t,F,I,v,H,S,f,Q,R){switch(f.tagName){case "b":Q.bold=!0;
break;case "i":Q.italic=!0;break;case "u":Q.underline=!0}for(var n=0;n<f.childNodes.length;n++){var N=f.childNodes[n];if(N.nodeType===3)N=new l0(F,I,v,H.id,N.nodeValue,S||n>0,g.sj(Q)?void 0:Q),R.push(N),H.N.push(N);else{var M={};Object.assign(M,Q);rh3(t,F,I,v,H,!0,N,M,R)}}},Ah_=function(t){var F=t.split(":");
t=0;F=g.l(F);for(var I=F.next();!I.done;I=F.next())t=t*60+Number(I.value);return t*1E3},kQO=function(t,F,I,v){v=Object.assign({Iq:0},v);
return new X_(t,F,I,"_"+e3++,v)},b0=function(t,F){g.c.call(this);
this.Z=t;this.r0=F;this.N=null;this.S=this.Z.Wi();this.logger=new g.eb("caps")},chI=function(t,F,I){if(typeof F==="string"||YmI(F))return[{trackData:F,
er:I}];if(typeof F==="string"&&F.substring(0,6)==="WEBVTT"||typeof F!=="string"&&wl3(F))return[{trackData:F,er:I}];var v=new DataView(F);if(v.byteLength<=8||v.getUint32(4)!==1718909296)return[];var H=g.GBu(v);if(t.S&&H){var S=g.tTK(H),f=g.Fle(H);H=H.BD;S&&H&&t.S.cG(H,S,f)}t=g.VQ(v,1835295092);if(!t||!t.length||!t[0].size)return[];S=[];for(f=0;f<t.length;f++)H=t[f],H=new Uint8Array(F,H.dataOffset,H.size-(H.dataOffset-H.offset)),H=g.yS(H),S.push({trackData:H,er:I+f*1E3});haO(v,S,I);return S=S.filter(function(Q){return!!Q.trackData})},
haO=function(t,F,I){var v=g.OT(t,0,1836476516),H=9E4;
v&&(H=g.TX(v)||9E4);v=0;for(var S=g.VQ(t,1836019558),f=0;f<S.length;f++){var Q=S[f];f<F.length&&(Q=g.OT(t,Q.dataOffset,1953653094))&&(Q=g.OT(t,Q.dataOffset,1952867444))&&(Q=g.Xs(Q)/H*1E3,f===0&&(v=Q),F[f].er=Q-v+I||I*f*1E3)}},P_I=function(t,F,I){t.N||(t.N=new mVE);
t=t.N.T(F,I);Math.random()<.01&&g.a4(Error("Deprecated subtitles format in web player: WebVTT"));return t},Jhy=function(t){var F={};
if(t=g.Z5(t))F.lang=t,g.X63.test(t)&&(F.Wv=1);return F},C_T=function(t){g.lH.call(this,t);
var F=this;this.Z=t;this.pF=[];this.TY={};this.iz={};this.j=!1;this.J="NONE";this.N=this.U=this.kP=this.X4=this.LF=null;this.Sa={aW:function(){F.aW()},
fz:function(S,f,Q,R){F.fz(S,f,Q,R)}};
this.S=null;this.r0=this.Z.K();this.videoData=this.Z.getVideoData();this.Mf=this.Z.j7();this.T={IK:{}};this.V={IK:{}};g.W8(this.videoData)?this.J="OFFLINE":$V3(this.videoData,this.Z)?this.J="SABR_LIVE":g.iyj(this.videoData,this.Z)?this.J="LIVE":this.videoData.captionTracks.length?this.J="INNERTUBE":this.videoData.w_&&(this.J="TTS");this.zY=this.r0.controlsType==="3";this.KF=new b0(this.Z,this.r0);this.D3=new g.BL(this);this.B=new g.b({D:"div",X:"ytp-caption-window-container",G:{id:"ytp-caption-window-container"}});
this.e7={top:0,right:0,bottom:0,left:0,width:1,height:1};var I=null,v=g.Kq("yt-html5-player-modules::subtitlesModuleData");v&&(I=new g.aj(v));this.storage=I;var H;this.IF=!((H=t.Oz())==null||!H.Hm());this.C=KrZ(this);this.Jh=!this.C&&this.zY&&this.IF&&(this.J==="LIVE"||this.J==="SABR_LIVE");g.P(this,this.KF);this.C?this.Z3=this.bz=null:(this.bz=new g.tv(this.a_,void 0,this),g.P(this,this.bz),this.Z3=new g.FW(this.Mzh,2E3,this),g.P(this,this.Z3));g.P(this,this.D3);g.H9(this.player,this.B.element,4);
g.P(this,this.B);this.C||this.D3.W(t,"resize",this.Y4);(this.ea=g.sh(this.r0)&&!g.Yu()&&!this.Z.isFullscreen()&&!this.C&&!this.Jh)&&this.D3.W(t,"resize",this.vNF);this.D3.W(t,"onPlaybackAudioChange",this.JNz);this.D3.W(t,g.iT("captions"),function(S){F.onCueRangeEnter(S)});
this.D3.W(t,g.t4("captions"),function(S){F.onCueRangeExit(S)});
bPE(this,B_I()||{});this.player.xd("onCaptionsModuleAvailable")},zaI=function(t){if(t.r0.L_===1||t.videoData.Ok===1||g.tC(t.videoData,"yt:cc")==="alwayson")return!0;
if(t.videoData.captionTracks.length)var F=t.getAudioTrack().S;if(t.r0.L_===2){if(g.pD(t.r0))var I=gd3(t);else if(t.storage)try{I=t.storage.get("module-enabled")}catch(H){t.storage.remove("module-enabled")}else I=null;if(I!=null)return!!I}I=Uzs(t.player.getAudioTrack(),g.pD(t.r0));var v=g.tC(t.videoData,"yt:cc");if(xVI(t)===void 0){if(I==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return v?v==="on":!0;if(I==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return v==="on"}else return v==="on";return F==="ON"||
g.tC(t.videoData,"yt:cc")==="on"},Cc=function(t,F){if(t.S&&(F===void 0||!F)||!t.videoData.captionTracks.length)return!1;
t=t.getAudioTrack();return!!t.N||t.S==="FORCED_ON"},xVI=function(t){var F=void 0,I=g.bO().G3(65);
if(g.pD(t.r0)&&I!=null){if(gd3(t)!=null)return!1;F=!I}return F},xN=function(t,F){if(!t.N)return null;
if(t.U&&t.U.J)return t.U.J;F=udG(t,F);F=g.FN(t.N.S,F);var I=null;if(Yg_(t.r0)){var v=t.Z.isInline()?void 0:g.ku("yt-player-caption-sticky-language");for(var H=[v,t.videoData.captionsLanguagePreference,t.r0.captionsLanguagePreference,g.tC(t.videoData,"yt:cc_default_lang")],S=!1,f=0;f<H.length;f++){var Q=H[f];if(Q){S=!0;for(var R=0;R<F.length;R++)if(g.Z5(F[R])===Q)return F[R];for(R=0;R<F.length;R++)if(g.Z5(F[R]).split("-")[0]===Q.split("-")[0])return F[R]}}if(S&&t.N&&(H=t.N.C,H.length))for(H=g.l(H),
S=H.next();!S.done;S=H.next())if(S=S.value,S.languageCode===v){I=S;break}}else for(v=[t.videoData.captionsLanguagePreference,t.r0.captionsLanguagePreference,g.tC(t.videoData,"yt:cc_default_lang")],H=0;H<v.length;H++)for(S=0;S<F.length;S++)if(g.Z5(F[S])===v[H])return F[S];v=null;t.U&&t.U.T&&(v=t.U.T);v||(v=F.find(function(n){return n.isDefault})||null);
v||(v=F[0]||gB(t));v&&I&&g.Z5(v).split("-")[0]!==I.languageCode.split("-")[0]&&(v=lA3(v,I));return v},gB=function(t){return t.U&&t.U.N},zA=function(t){var F=gB(t);
return!!F&&t.S===F},LrT=function(t,F){var I=t.Z.Oz().Qs().textTracks;
t=t.S.toString();for(var v=0;v<I.length;v++){var H=I[v];H.id===t&&(F?H.mode!=="showing"&&(H.mode="showing"):H.mode==="showing"&&(H.mode="disabled"))}},Z0=function(t,F,I){t.loaded&&t.unload();
I!=null&&(t.j=I,t.j&&(g.pD(t.r0)?u0(t,!!F):Lc(t,!!F)));F!==null||Cc(t,!0)||t.Rh(F,!!F,t.j?"m":"s");t.S=F;Cc(t)&&(t.S=gB(t));var v;ZP_(t,(v=t.S)!=null?v:void 0);t.load()},qm_=function(t,F){if(F instanceof X_){var I=t.TY[F.id];
I&&I.S!==F&&(I.dispose(),delete t.TY[F.id],I=null);I||(I=DVF(t,F))&&(t.TY[F.id]=I)}else I=F.windowId,t.iz[I]||(t.iz[I]=[]),t.iz[I].push(F)},DVF=function(t,F){var I=ifI(t);
if(!I)return null;var v=t.S?g.Z5(t.S):null;v&&g.X63.test(v)&&(F.params.Wv=1);var H=t.Mf.getPlayerSize();v=H.height*t.e7.height;H=H.width*t.e7.width;t.r0.playerStyle!=="google-live"||t.T.isDefault||Object.assign(F.params,t.T);switch(F.params.Iq!=null?F.params.Iq:F.N.length>1?1:0){case 1:return new AO(F,t.T,t.V,I.width,I.height,H,v,t.r0.experiments,t.mV.bind(t),t.Z);case 2:return new JO(F,t.T,t.V,I.width,I.height,H,v,t.r0.experiments,t.mV.bind(t),t.Z);default:return new NW(F,t.T,t.V,I.width,I.height,
H,v,t.r0.experiments,t.mV.bind(t),t.Z)}},bPE=function(t,F,I){I=I===void 0?!1:I;
var v=D0.IK;t.T={};Object.assign(t.T,D0);t.T.IK={};Object.assign(t.T.IK,v);t.V={IK:{}};var H=F.backgroundOverride?t.V:t.T,S=F.background||v.background;$N.test(S);H.IK.background=S;H=F.colorOverride?t.V:t.T;S=F.color||v.color;$N.test(S);H.IK.color=S;H=F.windowColorOverride?t.V:t.T;S=F.windowColor||D0.windowColor;$N.test(S);H.windowColor=S;H=F.backgroundOpacityOverride?t.V:t.T;S=F.backgroundOpacity;S==null&&(S=v.backgroundOpacity);H.IK.backgroundOpacity=S;H=F.fontSizeIncrementOverride?t.V:t.T;S=F.fontSizeIncrement;
S==null&&(S=v.fontSizeIncrement);H.IK.fontSizeIncrement=S;S=F.fontStyleOverride?t.V:t.T;H=F.fontStyle;H==null&&(H=v.bold&&v.italic?3:v.bold?1:v.italic?2:0);S=S.IK;switch(H){case 1:S.bold=!0;delete S.italic;break;case 2:delete S.bold;S.italic=!0;break;case 3:S.bold=!0;S.italic=!0;break;default:delete S.bold,delete S.italic}H=F.textOpacityOverride?t.V:t.T;S=F.textOpacity;S==null&&(S=v.textOpacity);H.IK.textOpacity=S;H=F.windowOpacityOverride?t.V:t.T;S=F.windowOpacity;S==null&&(S=D0.windowOpacity);H.windowOpacity=
S;H=F.charEdgeStyleOverride?t.V:t.T;S=F.charEdgeStyle;S==null&&(S=v.charEdgeStyle);H.IK.charEdgeStyle=S;H=F.fontFamilyOverride?t.V:t.T;S=F.fontFamily;S==null&&(S=v.fontFamily);H.IK.fontFamily=S;t.loaded&&t.Y4();I&&g.A9("yt-player-caption-display-settings",F,2592E3)},tM4=function(t,F){if(!t.N)return{};
if(F){g.sj(F)||t.z$(F.vss_id,"m");if(t.C||!g.HG(F))return;if(g.sj(F)){Z0(t,null,!0);return}for(var I,v=g.FN(t.N.S,!0),H=0;H<v.length;H++){var S=v[H];S.languageCode!==F.languageCode||I&&(S.languageName!==F.languageName||(S.captionId||"")!==(F.captionId||"")||g.uj(S)!==F.displayName)||(I=F.translationLanguage?lA3(S,F.translationLanguage):S)}t.oC(F.position);!I||I===t.S&&t.loaded||(F=g.eY(),v=g.Z5(I),F.length&&v===F[F.length-1]||(F.push(v),g.A9("yt-player-caption-language-preferences",F)),Yg_(t.r0)&&
!t.Z.isInline()&&g.A9("yt-player-caption-sticky-language",v,2592E3),Z0(t,I,!0))}else return t.loaded&&t.S&&!zA(t)?g.LD(t.S):{};return""},IBF=function(t,F,I){F&&!t.kP?(F=M73({Wv:0,
lang:"en"}),t.kP=[F,new l0(F.start,F.end-F.start,0,F.id,I!=null?I:"Captions look like this")],t.player.aK(t.kP)):!F&&t.kP&&(FWG(t,t.kP),t.kP=null)},FWG=function(t,F){t.player.hQ(F);
F=g.l(F);for(var I=F.next();!I.done;I=F.next())g.WG(t.pF,I.value);RU(t.bz)},ZP_=function(t,F){t.r0.Y("html5_modify_caption_vss_logging")&&(t.videoData.yG=F)},ifI=function(t){var F=t.Mf.getVideoContentRect(!0).height,I=t.Mf.getVideoContentRect(!0).width;
if(!F||!I)return null;F*=t.e7.height;I*=t.e7.width;return{width:I,height:F}},Lc=function(t,F){if(t.storage)try{t.storage.set("module-enabled",F)}catch(I){}},u0=function(t,F){t.Z.isInline()||g.A9("yt-player-sticky-caption",F,2592E3)},gd3=function(t){if(!t.Z.isInline())return g.ku("yt-player-sticky-caption")},KrZ=function(t){var F,I=!((F=t.Z.Oz())==null||!F.mj());
return t.zY&&I&&t.J!=="LIVE"&&t.J!=="SABR_LIVE"},udG=function(t,F){g.NX(t.videoData)&&(F=!0);
F||(F=t.J==="TTS"?!1:t.J==="INNERTUBE"?!1:!0);return F||t.r0.Y("web_deprecate_always_includes_asr_setting")&&g.pD(t.r0)?!0:!!g.bO().G3(66)};
g.XN.prototype.hX=g.St(71,function(){return!1});
g.XN.prototype.U9=g.St(70,function(){});
g.e2.prototype.U9=g.St(69,function(t,F,I){var v=this;this.Et();F=this.Ky(t,F);var H=this.fF.K().Y("html5_report_captions_ctmp_qoe"),S=(0,g.ef)();this.qN();yJE(this,F,{format:"RAW",onSuccess:function(f){v.N=null;if(H){var Q=(f.responseText.length/1024).toFixed(),R=(0,g.ef)();v.videoData.Nf("capresp",{ms:R-S,kb:Q})}I.fz(f.responseText,t)},
onError:H?function(f){var Q;f=(Q=f==null?void 0:f.status)!=null?Q:0;v.videoData.Nf("capfail",{status:f})}:void 0,
withCredentials:!0})});
g.Vs.prototype.U9=g.St(68,function(t,F,I){var v=this;this.Et();F=this.Ky(t,F);this.qN();this.N=g.Bw(F,{format:"RAW",onSuccess:function(H){v.N=null;I.fz(H.responseText,t)},
withCredentials:!0})});
g.xI.prototype.E7=g.St(67,function(){for(var t=g.fz(document,"track",void 0,this.N),F=0;F<t.length;F++)g.yZ(t[F])});
g.cn.prototype.E7=g.St(66,function(){this.mediaElement.E7()});
g.xI.prototype.Hm=g.St(65,function(){return!(!this.N.textTracks||!this.N.textTracks.addEventListener)});
g.cn.prototype.Hm=g.St(64,function(){return this.mediaElement.Hm()});
g.xI.prototype.mj=g.St(63,function(){return!!this.N.textTracks});
g.cn.prototype.mj=g.St(62,function(){return this.mediaElement.mj()});
g.xI.prototype.BR=g.St(61,function(t){for(var F=0;F<t.length;F++)this.N.appendChild(t[F])});
g.cn.prototype.BR=g.St(60,function(t){this.mediaElement.BR(t)});
g.f8.prototype.cG=g.St(59,function(t,F,I){this.f$.cG(t,F,I)});
g.qO.prototype.cG=g.St(58,function(t,F,I){this.S.set(t,{ol:F,J$:I})});
g.iK.prototype.cG=g.St(57,function(t,F,I){this.e7.cG(t,F,I)});
g.f8.prototype.BB=g.St(56,function(t){return this.f$.BB(t)});
g.iK.prototype.BB=g.St(55,function(t){var F=2;this.C.has(t)?F=0:g.n1i(this,t)&&(F=1);return F});
g.ZV.prototype.Im=g.St(43,function(t){var F=this.app.Ez({playerType:void 0});return F?F.Im(t):!1});
g.RC.prototype.Im=g.St(42,function(t){return this.v3.vj.Im(t)});
g.as.prototype.Im=g.St(41,function(t){return this.W9().some(function(F){return F.namespace===t})});
g.C2.prototype.Im=g.St(40,function(){return!1});
g.ZV.prototype.z$=g.St(38,function(t,F){this.app.nF().z$(t,F)});
g.RC.prototype.z$=g.St(37,function(t,F){this.v3.z$(t,F)});
g.ix.prototype.z$=g.St(36,function(t,F){t=[t,F];g.qi(this,g.FM(this.provider),"cfi",t)});
g.$5.prototype.z$=g.St(35,function(t,F){this.qoe&&this.qoe.z$(t,F)});
g.Ff.prototype.z$=g.St(34,function(t,F){this.sZ.z$(t,F)});
g.C2.prototype.z$=g.St(33,function(){});
g.ZV.prototype.Rh=g.St(32,function(t,F,I){this.app.nF().Rh(t,F,I)});
g.RC.prototype.Rh=g.St(31,function(t,F,I){this.v3.Rh(t,F,I)});
g.ix.prototype.Rh=g.St(30,function(t,F,I){if(this.bz!==t||this.lk!==F)F=F==="rawcc"?"":F,I=[t,F,this.bz,I],g.qi(this,g.FM(this.provider),"cfs",I),this.bz=t,this.lk=F});
g.$5.prototype.Rh=g.St(29,function(t,F,I){this.qoe&&this.qoe.Rh(t,F,I)});
g.Ff.prototype.Rh=g.St(28,function(t,F,I){this.sZ.Rh(t,F,I)});
g.C2.prototype.Rh=g.St(27,function(){});
g.jB.prototype.vM=g.St(12,function(){return this.j});
g.Ew.prototype.vM=g.St(11,function(){return this.nF().Wi()});
g.ZV.prototype.Wi=g.St(10,function(){return this.app.vM()});
g.RC.prototype.Wi=g.St(9,function(){return this.v3.Wi()});
g.Ff.prototype.Wi=g.St(8,function(){var t;return((t=this.loader)==null?void 0:t.vM())||null});
g.C2.prototype.Wi=g.St(7,function(){return null});
g.HR.prototype.jY=g.St(1,function(t){return(t=this.Z1(t))?t.N:0});
g.rl.prototype.jY=g.St(0,function(){return 0});
var dzI=/#(.)(.)(.)/,ezO=/^#(?:[0-9a-f]{3}){1,2}$/i,rJZ={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};nc.prototype.contains=function(t){t=g.bs(this.segments,t);return t>=0||t<0&&(-t-1)%2===1};
nc.prototype.length=function(){return this.segments.length/2};
g.U(mzZ,g.c);g.y=mzZ.prototype;g.y.xP=function(){g.c.prototype.xP.call(this);this.S&&this.S.cancel()};
g.y.XG=function(){this.seekTo(this.player.getCurrentTime())};
g.y.seekTo=function(t){t-=this.player.Ki();var F=this.N;this.N=g.OO(this.kP.WL(t).Ut);F!==this.N&&this.U&&this.U()};
g.y.reset=function(){this.J=new nc;this.V=-1;this.S&&(this.S.cancel(),this.S=null)};
g.y.IN=function(){this.Et();var t;if(t=this.N!=null)t=this.N,t=t.N.Mo(t);if(t&&!this.S&&!(this.N&&this.N.startTime-this.player.getCurrentTime()>30)){t=this.N;t=t.N.ME(t);var F=t.Ut[0],I;if((I=this.player.getVideoData())==null?0:I.enableServerStitchedDai)if(I=this.player.Wi()){var v=F.N.info.id,H=F.P3,S=t.Ut[0].C;if(this.policy.bz){if(I=I.Hh(S,H,v,3))t.J=I}else if(v=I.HO(S,H,v,3))if(I=I.BB(H),I===0)v&&(t.N=new g.ZR(v));else if(I===2){this.B.start();aAO(this)&&this.seekTo(this.player.getCurrentTime());
return}}F.N.index.RE(F.P3)?(this.J.contains(t.Ut[0].P3)||w5E(this,t),this.N=g.OO(t.Ut)):aAO(this)&&this.seekTo(this.player.getCurrentTime())}this.B.start()};
g.U(s2,g.XN);g.y=s2.prototype;g.y.U9=function(t,F,I){var v=this;this.qN();F=kG4(this,t.getId());F||(F=t.languageCode,F=this.N.isManifestless?hz_(this,F,"386"):hz_(this,F));if(F){var H=(F.index.jY(F.index.aE())-F.index.getStartTime(F.index.aE()))*1E3,S=new g.t_k(this.Z.K());this.J=new mzZ(S,this.Z,F,function(f,Q){I.fz(f,t,Q,H)},this.B||g.Iv(F.info),function(){v.J&&v.J.reset();
v.V=!0})}};
g.y.hX=function(){var t=this.V;this.V=!1;return t};
g.y.bx=function(t){var F=this.Z.K().Y("html5_fallback_if_rawcc_missing");var I=this.N.N.rawcc!=null;if(!this.B||!I&&F)F=this.N.isManifestless?AJI(this,"386"):AJI(this);else{if(!I){g.dl(this.logger,386248249,"rawcc used but unavailable");return}F=[new g.zs({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.zs({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}F=g.l(F);
for(I=F.next();!I.done;I=F.next())g.WM(this.S,I.value);t.aW()};
g.y.qN=function(){this.J&&(this.J.dispose(),this.J=null)};
g.y.Ky=function(){return""};
var $N=/^#(?:[0-9a-f]{3}){1,2}$/i;var JJT=["left","right","center","justify"];g.U(NW,g.b);g.y=NW.prototype;g.y.Sg=function(t,F){this.zY=t;this.KF=F;var I=g.t7(this.element,this.element.parentElement);this.LF=t-I.x;this.Mf=F-I.y};
g.y.eg=function(t,F){if(t!==this.zY||F!==this.KF){g.Rj(this.element,"ytp-dragging")||g.nq(this.element,"ytp-dragging");var I=g.I9(this.element);t=t-this.LF-.02*this.TN;var v=F-this.Mf-.02*this.AN,H=(t+I.width/2)/this.maxWidth*3;H=Math.floor(g.J$(H,0,2));var S=(v+I.height/2)/this.maxHeight*3;S=Math.floor(g.J$(S,0,2));F=H+S*3;t=(t+H/2*I.width)/this.maxWidth;t=g.J$(t,0,1)*100;I=(v+S/2*I.height)/this.maxHeight;I=g.J$(I,0,1)*100;this.S.params.Ij=F;this.S.params.Dv=I;this.S.params.bb=t;this.S.params.isDefault=
!1;this.N.Ij=F;this.N.Dv=I;this.N.bb=t;this.N.isDefault=!1;this.e7.Ij=F;this.e7.Dv=I;this.e7.bb=t;this.e7.isDefault=!1;this.ey()}};
g.y.NZ=function(){g.NG(this.element,"ytp-dragging")};
g.y.ey=function(){this.Oc(this.V)};
g.y.Oc=function(t){var F=this.IF?0:Math.min(this.w3(),this.maxWidth),I=this.qj(),v=this.IF;if(v){var H=getComputedStyle(this.J.parentNode);H=oU(H.borderLeftWidth)+oU(H.borderRightWidth)+oU(H.paddingLeft)+oU(H.paddingRight)}else H=0;var S=H;H="";this.S.params.Wv===3&&(H="rotate(180deg)");var f=v?"calc(96% - "+S+"px)":"96%";g.gN(this.element,{top:0,left:0,right:"",bottom:"",width:F?F+"px":"",height:I?I+"px":"","max-width":f,"max-height":f,margin:"",transform:""});this.l$(t);H={transform:H,top:"",left:"",
width:F?F+"px":"",height:I?I+"px":"","max-width":"","max-height":""};var Q=this.N.bb*.96+2;f=this.N.Ij;switch(f){case 0:case 3:case 6:(v=this.N.IK.fontSizeIncrement)&&v>0&&this.N.Wv!==2&&this.N.Wv!==3&&(Q=Math.max(Q/(1+v*2),2));H.left=Q+"%";break;case 1:case 4:case 7:H.left=Q+"%";Q=this.J.offsetWidth;F||Q?(F=F||Q+1,H.width=F+"px",H["margin-left"]=v?F/-2-S/2+"px":F/-2+"px"):H.transform+=" translateX(-50%)";break;case 2:case 5:case 8:H.right=100-Q+"%"}v=this.N.Dv*.96+2;switch(f){case 0:case 1:case 2:H.top=
v+"%";break;case 3:case 4:case 5:H.top=v+"%";(I=I||this.element.clientHeight)?(H.height=I+"px",H["margin-top"]=I/-2+"px"):H.transform+=" translateY(-50%)";break;case 6:case 7:case 8:H.bottom=100-v+"%"}g.gN(this.element,H);if(this.C){I=this.J.offsetHeight;v=1;for(F=0;F<t.length;F++)H=t[F],typeof H.text==="string"&&(v+=H.text.split("\n").length-1,H.append||F===0||v++);I/=v;this.C.style.height=I+"px";this.C.style.width=I+"px";this.element.style.paddingLeft=I+5+"px";this.element.style.paddingRight=I+
5+"px";t=Number(this.element.style.marginLeft.replace("px",""))-I-5;I=Number(this.element.style.marginRight.replace("px",""))-I-5;this.element.style.marginLeft=t+"px";this.element.style.marginRight=I+"px"}};
g.y.l$=function(t){var F;for(F=0;F<t.length&&t[F]===this.V[F];F++);if(this.D3||this.V.length>F)F=0,this.D3=!1,this.V=[],this.B=this.bz=this.pF=null,g.Oy(this.J);for(;F<t.length;F++)xzy(this,t[F])};
g.y.w3=function(){return 0};
g.y.qj=function(){return 0};
g.y.toString=function(){return g.b.prototype.toString.call(this)};uEO.prototype.clear=function(){this.T=this.time=this.mode=0;this.N=[];this.reset()};
uEO.prototype.reset=function(){this.mode=0;this.J.reset(0);this.C.reset(1)};
var LqI=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];MW.prototype.set=function(t){this.type=t};
MW.prototype.get=function(){return this.type};
E2.prototype.clear=function(){this.state=0};
E2.prototype.update=function(){this.state=this.state===2?1:0};
E2.prototype.Yd=function(){return this.state!==0};
E2.prototype.matches=function(t,F){return this.Yd()&&t===this.NQ&&F===this.xu};
t7E.prototype.reset=function(){this.timestamp=this.N=0};
O2.prototype.updateTime=function(t){for(var F=1;F<=15;++F)for(var I=1;I<=32;++I)this.T[F][I].timestamp=t};
O2.prototype.debugString=function(){for(var t="\n",F=1;F<=15;++F){for(var I=1;I<=32;++I){var v=this.T[F][I];t=v.N===0?t+"_":t+String.fromCharCode(v.N)}t+="\n"}return t};
O2.prototype.reset=function(t){for(var F=0;F<=15;F++)for(var I=0;I<=32;I++)this.T[F][I].reset();this.J=t;this.N=0;this.S=this.row=1};
var Fr3=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],IK0=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],vdZ=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],HPZ=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];GQZ.prototype.reset=function(t,F){this.C=F;this.style.set(2);this.S=this.V;this.J=this.B;this.N=this.S;var I=(t<<2)+(F<<1);this.V.reset(I);this.B.reset(I);this.text.reset((t<<2)+(F<<1)+1)};
zzI.prototype.reset=function(t){this.C=t;this.S.clear();this.J=this.T;this.T.reset(t,0);this.V.reset(t,1)};sJ4.prototype.J=function(){};g.U(l0,g.DX);l0.prototype.toString=function(){return g.DX.prototype.toString.call(this)};g.U(Wx,g.c);Wx.prototype.reset=function(){};g.U(X_,g.DX);X_.prototype.toString=function(){return g.DX.prototype.toString.call(this)};
var e3=0;g.U(dB,Wx);dB.prototype.reset=function(){this.B={};this.S=this.N=null;this.V=!0};
dB.prototype.T=function(t,F){t=t.firstChild;t.getAttribute("format");F=F||0;Number.isFinite(F);t=Array.from(t.childNodes);t=g.l(t);for(var I=t.next();!I.done;I=t.next())if(I=I.value,I.nodeType===1)switch(I.tagName){case "head":var v=I;break;case "body":var H=I}if(v)for(v=Array.from(v.childNodes),v=g.l(v),t=v.next();!t.done;t=v.next())if(t=t.value,t.nodeType===1)switch(t.tagName){case "pen":I=t.getAttribute("id");var S=this.pens,f={},Q=t.getAttribute("p");Q&&Object.assign(f,this.pens[Q]);Q=pc(t,"b");
Q!=null&&(f.bold=Q);Q=pc(t,"i");Q!=null&&(f.italic=Q);Q=pc(t,"u");Q!=null&&(f.underline=Q);Q=Bx(t,"et");Q!=null&&(f.charEdgeStyle=Q);Q=Bx(t,"of");Q!=null&&(f.offset=Q);Q=m$(t,"bc");Q!=null&&(f.background=Q);Q=m$(t,"ec");Q!=null&&(f.y6=Q);Q=m$(t,"fc");Q!=null&&(f.color=Q);Q=Bx(t,"fs");Q!=null&&Q!==0&&(f.fontFamily=Q);Q=VI(t,"sz");Q!==void 0&&(f.fontSizeIncrement=Q/100-1);Q=VI(t,"bo");Q!==void 0&&(f.backgroundOpacity=Q/255);Q=VI(t,"fo");Q!==void 0&&(f.textOpacity=Q/255);Q=Bx(t,"rb");Q!=null&&Q!==10&&
Q!==0&&(f.dK=Q>10?Q-1:Q);t=Bx(t,"hg");t!=null&&(f.c_=t);S[I]=f;break;case "ws":I=t.getAttribute("id");this.U[I]=EdI(this,t);break;case "wp":I=t.getAttribute("id"),this.j[I]=OP0(this,t)}if(H){v=[];H=Array.from(H.childNodes);H=g.l(H);for(t=H.next();!t.done;t=H.next())if(t=t.value,t.nodeType===1)switch(t.tagName){case "w":this.N=TE0(this,t,F,!1);(t=this.B[this.N.id])&&t.end>this.N.start&&(t.end=this.N.start);this.B[this.N.id]=this.N;v.push(this.N);break;case "p":var R=t;Q=F;I=[];S=R.getAttribute("w")||
this.C;f=!!pc(R,"a");Q=(VI(R,"t")||0)+Q;var n=VI(R,"d")||5E3;f||(!this.V&&this.S&&this.S.windowId===S&&this.S.end>Q&&(this.S.end=Q),this.S&&this.S.text==="\n"&&(this.S.text=""));var N=f?6:5,M=R.getAttribute("p");M=M?this.pens[M]:null;var E=Array.from(R.childNodes);E.length&&(this.V=R.getAttribute("d")!=null);for(R=0;R<E.length;R++){var O=E[R],T=void 0;R>0&&(f=!0);var W=void 0;O.nodeType===1&&(W=O);if(W&&W.tagName==="s"){if((O=(O=W.getAttribute("p"))?this.pens[O]:null)&&O.dK&&(O.dK===1?(O=E.slice(R,
R+4),O.length===4&&(T=odG(Q,n,S,f,N,O,this.pens),R+=3)):T=odG(Q,n,S,f,N,[W],this.pens)),!T){var e=W;T=Q;W=n;O=S;var B=f,p=N,r=e.textContent?e.textContent:"",h=e.getAttribute("p");h=h?this.pens[h]:null;e=VI(e,"t")||0;T=new l0(T+e,W-e,p,O,r,B,h)}}else T=new l0(Q,n,N,S,O.textContent||"",f,M);I.push(T);this.S=T}if(I.length>0)for(I[0].windowId===this.C&&(this.N=TE0(this,t,F,!0),v.push(this.N)),t=g.l(I),I=t.next();!I.done;I=t.next())I=I.value,I.windowId=this.N.id,this.N.N.push(I),v.push(I)}F=v}else F=[];
return F};var v$4=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.U(aU,Wx);aU.prototype.reset=function(){this.S.clear()};
aU.prototype.T=function(t,F){var I=JSON.parse(t);if(!I)return[];if(I.pens){t=0;for(var v=g.l(I.pens),H=v.next();!H.done;H=v.next()){H=H.value;var S={},f=H.pParentId;f&&Object.assign(S,this.N.get(f));H.bAttr&&(S.bold=!0);H.iAttr&&(S.italic=!0);H.uAttr&&(S.underline=!0);f=H.ofOffset;f!=null&&(S.offset=f);H.szPenSize!==void 0&&(S.fontSizeIncrement=H.szPenSize/100-1);f=H.etEdgeType;f!=null&&(S.charEdgeStyle=f);H.ecEdgeColor!==void 0&&(S.y6=wB(H.ecEdgeColor));f=H.fsFontStyle;f!=null&&f!==0&&(S.fontFamily=
f);H.fcForeColor!==void 0&&(S.color=wB(H.fcForeColor));H.foForeAlpha!==void 0&&(S.textOpacity=H.foForeAlpha/255);H.bcBackColor!==void 0&&(S.background=wB(H.bcBackColor));H.boBackAlpha!==void 0&&(S.backgroundOpacity=H.boBackAlpha/255);(f=H.rbRuby)&&f!==10&&(S.dK=f>10?f-1:f,S.textEmphasis=v$4.get(S.dK));H.hgHorizGroup&&(S.c_=H.hgHorizGroup);this.N.set(t++,S)}}if(I.wsWinStyles)for(t=0,v=g.l(I.wsWinStyles),H=v.next();!H.done;H=v.next())H=H.value,S={},(f=H.wsParentId)?Object.assign(S,this.C.get(f)):Object.assign(S,
this.V),H.mhModeHint!==void 0&&(S.Iq=H.mhModeHint),H.juJustifCode!==void 0&&(S.textAlign=H.juJustifCode),H.pdPrintDir!==void 0&&(S.Wv=H.pdPrintDir),H.sdScrollDir!==void 0&&(S.Tl=H.sdScrollDir),H.wfcWinFillColor!==void 0&&(S.windowColor=wB(H.wfcWinFillColor)),H.wfoWinFillAlpha!==void 0&&(S.windowOpacity=H.wfoWinFillAlpha/255),this.C.set(t++,S);if(I.wpWinPositions)for(t=0,v=g.l(I.wpWinPositions),H=v.next();!H.done;H=v.next())H=H.value,S={},(f=H.wpParentId)&&Object.assign(S,this.J.get(f)),H.ahHorPos!==
void 0&&(S.bb=H.ahHorPos),H.apPoint!==void 0&&(S.Ij=H.apPoint),H.avVerPos!==void 0&&(S.Dv=H.avVerPos),H.ccCols!==void 0&&(S.Q7=H.ccCols),H.rcRows!==void 0&&(S.Z8=H.rcRows),this.J.set(t++,S);if(I.events){t=[];I=g.l(I.events);for(v=I.next();!v.done;v=I.next()){var Q=v.value;H=(Q.tStartMs||0)+F;S=Q.dDurationMs||0;if(Q.id)f=String(Q.id),v=yhI(this,Q,H,S,f),t.push(v),this.S.set(f,v);else{Q.wWinId?f=Q.wWinId.toString():(f="_"+e3++,v=yhI(this,Q,H,S,f),t.push(v),this.S.set(f,v));v=t;var R=Q;S===0&&(S=5E3);
Q=this.S.get(f);var n=!!R.aAppend,N=n?6:5,M=R.segs,E=null;R.pPenId&&(E=this.N.get(R.pPenId));for(R=0;R<M.length;R++){var O=M[R],T=O.utf8;if(T){var W=O.tOffsetMs||0,e=null;O.pPenId&&(e=this.N.get(O.pPenId));if((Q.params.Iq!=null?Q.params.Iq:Q.N.length>1?1:0)===2&&n&&T==="\n")continue;O=null;var B=[],p;if(p=e&&e.dK===1){p=M;var r=R;if(r+3>=p.length||!p[r+1].pPenId||!p[r+2].pPenId||!p[r+3].pPenId)p=!1;else{var h=p[r+1].pPenId;(h=this.N.get(h))&&h.dK&&h.dK===2?(h=p[r+2].pPenId,h=this.N.get(h),!h||!h.dK||
h.dK<3?p=!1:(h=p[r+3].pPenId,p=(h=this.N.get(h))&&h.dK&&h.dK===2?!0:!1)):p=!1}}if(p)W=M[R+1].utf8,O=M[R+3].utf8,p=M[R+2].utf8,r=this.N.get(M[R+2].pPenId),T=NEy(T,W,p,O,r),O=new l0(H,S,N,f,T,n,e),R+=3;else{if(T.indexOf("<")>-1){var J=void 0;B=e;p=E;r=H;h=S;var Z=W,C=N,vi=n,QT=[],Hi=g.Ly("<html>"+T+"</html>");if(!Hi.getElementsByTagName("parsererror").length&&((J=Hi.firstChild)==null?0:J.childNodes.length))for(J=g.l(Hi.firstChild.childNodes),Hi=J.next();!Hi.done;Hi=J.next()){Hi=Hi.value;var sK=void 0,
tc=void 0,UK=(tc=(sK=Hi.textContent)==null?void 0:sK.replace(/\n/g,""))!=null?tc:"";if(Hi.nodeType!==3||UK&&UK.match(/^ *$/)==null){sK={};Object.assign(sK,B||p);tc=void 0;switch((tc=Hi)==null?void 0:tc.tagName){case "b":sK.bold=!0;break;case "i":sK.italic=!0;break;case "u":sK.underline=!0}QT.push(new l0(r+Z,h-Z,C,Q.id,UK,vi,sK))}}B=QT}B.length||(B=[new l0(H+W,S-W,N,Q.id,T,n,e||E)])}if(B.length)for(n=g.l(B),e=n.next();!e.done;e=n.next())e=e.value,v.push(e),Q.N.push(e);else O&&(v.push(O),Q.N.push(O))}n=
!0}}}F=t}else F=[];return F};g.U(rB,g.XN);rB.prototype.U9=function(t,F,I){X54(this.videoData.videoId,t.vssId,I.fz)};
rB.prototype.bx=function(t){if(this.audioTrack)for(var F=g.l(this.audioTrack.captionTracks),I=F.next();!I.done;I=F.next())g.WM(this.S,I.value);t.aW()};g.U(AO,NW);AO.prototype.l$=function(t){var F=this.S.N;NW.prototype.l$.call(this,t);for(t=t.length;t<F.length;t++){var I=F[t];if(S&&I.N===H)var v=S;else{v={};Object.assign(v,I.N);Object.assign(v,Hfs);var H=I.N;var S=v}xzy(this,I,v)}};
var Hfs={hA:!0};g.U(kN,sJ4);kN.prototype.J=function(t,F,I,v,H){if(I<v){var S="_"+e3++;I=I/1E3-this.V;v=v/1E3-this.V;t=new X_(I,v-I,5,S,{textAlign:0,Ij:0,bb:F*2.5,Dv:t*5.33});H=new l0(I,v-I,5,S,H);this.S.push(t);this.S.push(H)}};
g.U(Px,Wx);Px.prototype.T=function(t){t=new kN(t,t.byteLength,this.S);if(UVI(t)){for(;t.byteOffset<t.N.byteLength;)for(t.version===0?t.T=cx(t)*(1E3/45):t.version===1&&(t.T=cx(t)*4294967296+cx(t)),t.C=hO(t);t.C>0;t.C--){var F=hO(t),I=hO(t),v=hO(t);F&4&&(F&3)===this.track&&(this.track===0||this.track===1)&&(F=this.N,F.N.push({time:t.T,type:this.track,Oq:I,Uq:v,order:F.N.length}))}iPE(this.N,t);return t.S}return[]};
Px.prototype.reset=function(){this.N.clear()};g.U(JO,NW);g.y=JO.prototype;g.y.ey=function(){g.ve(this.Sa)};
g.y.yK=function(){this.element.removeEventListener("transitionend",this.yK,!1);g.NG(this.element,"ytp-rollup-mode");this.Oc(this.a7,!0)};
g.y.qj=function(){return this.T?this.kP:this.U};
g.y.w3=function(){return this.T?this.U:this.kP};
g.y.Oc=function(t,F){this.a7=t;if(this.S.params.Z8){for(var I=0,v=0;v<this.V.length&&I<t.length;v++)this.V[v]===t[I]&&I++;I>0&&I<t.length&&(t=this.V.concat(t.slice(I)));this.ea=this.kP;this.U=this.kP=0;NW.prototype.Oc.call(this,t);XlO(this,F)}NW.prototype.Oc.call(this,t)};eaE.prototype.unload=function(){this.N!=null&&(this.Z.removeEventListener("sabrCaptionsDataLoaded",this.N),this.N=null);this.Fe=[];this.Z.publish("sabrCaptionsBufferedRangesUpdated",this.Fe)};
eaE.prototype.lG=function(t){return{formatId:g.Hp(t.info.N.info,this.o7),P3:t.info.P3+(this.o7?0:1),startTimeMs:t.info.C*1E3,durationMs:t.info.j*1E3}};g.U(Kc,g.XN);Kc.prototype.U9=function(t,F,I){this.qN();F=t.getId();F=F!=null&&F in this.N.N?this.N.N[F]:null;F||(F=t.languageCode,F=this.N.isManifestless?BEZ(this,F,"386"):BEZ(this,F));F&&(this.J=t,this.V=F,V7E(this.B,I),this.Z.publish("sabrCaptionsTrackChanged",g.Hp(F.info,this.N.o7)))};
Kc.prototype.bx=function(t){var F=this.N.isManifestless?plF(this,"386"):plF(this);F=g.l(F);for(var I=F.next();!I.done;I=F.next())g.WM(this.S,I.value);t.aW()};
Kc.prototype.qN=function(){this.J&&(this.J=this.V=null,this.B.unload(),this.Z.publish("sabrCaptionsTrackChanged",null))};
Kc.prototype.Ky=function(){return""};var aKE="WEBVTT".split("").map(function(t){return t.charCodeAt(0)});
g.U(mVE,Wx);
mVE.prototype.T=function(t,F){t instanceof ArrayBuffer&&(t=g.yS(new Uint8Array(t)));var I=[];t=t.split(SB0);for(var v=1;v<t.length;v++){var H=t[v],S=F;if(H!==""&&!j3y.test(H)){var f=fBE.exec(H);if(f&&f.length>=4){var Q=Ah_(f[1]),R=Ah_(f[2])-Q;Q+=S;var n=(f=f[3])?f.split(" "):[];f={};var N=null;var M="";var E=null,O="";n=g.l(n);for(var T=n.next();!T.done;T=n.next())if(T=T.value.split(":"),T.length===2){var W=T[1];switch(T[0]){case "line":T=W.split(",");T[0].endsWith("%")&&(N=T[0],f.Dv=Number.parseInt(N,
10),T.length===2&&(M=T[1].trim()));break;case "position":T=W.split(",");E=T[0];f.bb=Number.parseInt(E,10);T.length===2&&(O=T[1].trim());break;case "align":switch(W){case "start":f.textAlign=0;break;case "middle":f.textAlign=2;break;case "end":f.textAlign=1}}}N||M||(M="end");if(!E)switch(f.textAlign){case 0:f.bb=0;break;case 1:f.bb=100;break;case 2:f.bb=50}if(f.textAlign!=null){N=0;switch(M){case "center":N+=3;break;case "end":N+=6;break;default:N+=0}switch(O){case "line-left":N+=0;break;case "center":N+=
1;break;case "line-right":N+=2;break;default:switch(f.textAlign){case 0:N+=0;break;case 2:N+=1;break;case 1:N+=2}}M=N<0||N>8?7:N;f.Ij=M}H=H.substring(fBE.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");O=f;f=H;H={};if(f.indexOf("<")<0&&f.indexOf("&")<0)S=kQO(Q,R,5,O),R=new l0(Q,R,5,S.id,f,!1,g.sj(H)?void 0:H),I.push(S),I.push(R),S.N.push(R);else for(M=f.split(Ge0),M.length===1?(f=5,O=kQO(Q,R,f,O)):(N=f=6,O=Object.assign({Q7:32},O),O=new X_(Q,R,N,"_"+e3++,O)),I.push(O),N=Q,E=0;E<M.length;E++)n=M[E],
E%2===0?(T=g.Ly("<html>"+n+"</html>"),T.getElementsByTagName("parsererror").length?(W=T.createElement("span"),W.appendChild(T.createTextNode(n))):W=T.firstChild,rh3(this,N,R-(N-Q),f,O,E>0,W,H,I)):N=Ah_(n)+S}fBE.lastIndex=0}}return I};
var j3y=/^NOTE/,SB0=/(?:\r\n|\r|\n){2,}/,fBE=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Ge0=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.U(b0,g.c);b0.prototype.clear=function(){this.N&&this.N.dispose();this.N=null};
b0.prototype.reset=function(){this.N&&this.N.reset()};
b0.prototype.xP=function(){g.c.prototype.xP.call(this);this.clear()};var D0={windowColor:"#080808",windowOpacity:0,textAlign:2,Ij:7,bb:50,Dv:100,isDefault:!0,IK:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.U(C_T,g.lH);g.y=C_T.prototype;g.y.xP=function(){if(this.C||this.Jh){var t=this.Z.Oz();t&&!t.Et()&&t.E7()}else IBF(this,!1);g.lH.prototype.xP.call(this)};
g.y.hH=function(){return this.r0.Y("html5_honor_caption_availabilities_in_audio_track")&&this.J!=="LIVE"&&this.J!=="SABR_LIVE"};
g.y.KB=function(){if(this.zY)return this.C||this.Jh;var t=this.getAudioTrack();if(this.hH()){if(!t.captionTracks.length)return!1;if(!this.N)return!0}t=Uzs(t,g.pD(this.r0));return t==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:t==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?Cc(this):xVI(this)||Cc(this)?!0:zaI(this)};
g.y.load=function(){g.lH.prototype.load.call(this);this.U=this.getAudioTrack();if(this.N)this.S&&(this.KF.clear(),this.C?LrT(this,!0):this.player.getPresentingPlayerType()!==3&&this.N.U9(this.S,"json3",this.Sa),this.C||this.Jh||zA(this)||this.player.xd("captionschanged",g.LD(this.S)));else{var t;this.J==="OFFLINE"?t=new rB(this.player,this.videoData,this.getAudioTrack()):this.J==="SABR_LIVE"?t=new Kc(this.videoData.N,this.player):this.J==="LIVE"?t=new s2(this.videoData.N,this.player):this.J==="INNERTUBE"?
t=new g.e2(this.player,this.videoData,this.getAudioTrack()):t=new g.Vs(this.player,this.videoData.w_,this.videoData.videoId,g.RQt(this.videoData),this.videoData.Hy,this.videoData.eventId);this.N=t;g.P(this,this.N);this.N.bx(this.Sa)}};
g.y.unload=function(){this.C&&this.S?LrT(this,!1):(this.Z3&&g.He(this.Z3),this.player.qb("captions"),this.pF=[],this.N&&this.N.qN(),this.KF.clear(),this.kP&&this.player.aK(this.kP),this.Y4());g.lH.prototype.unload.call(this);this.player.Le();this.player.xd("captionschanged",{})};
g.y.create=function(){this.KB()&&this.load();var t;a:{var F,I,v;if(this.r0.Y("web_player_nitrate_promo_tooltip")&&((F=this.videoData.getPlayerResponse())==null?0:(I=F.captions)==null?0:(v=I.playerCaptionsTracklistRenderer)==null?0:v.enableTouchCaptionsNitrate)){var H,S;if(F=(t=this.videoData.getPlayerResponse())==null?void 0:(H=t.captions)==null?void 0:(S=H.playerCaptionsTracklistRenderer)==null?void 0:S.captionTracks)for(t=g.l(F),H=t.next();!H.done;H=t.next())if(H=H.value,H.kind==="asr"&&H.languageCode===
"en"){t=!0;break a}}t=!1}t&&this.Z.publish("showpromotooltip",this.B.element)};
g.y.aW=function(){var t=Uzs(this.player.getAudioTrack(),g.pD(this.r0));var F=t==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?xN(this,this.j):t==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&Cc(this)?gB(this):xVI(this)||this.j||zaI(this)?xN(this,this.j):Cc(this)?gB(this):null;if(this.C||this.Jh){var I=g.FN(this.N.S,!0);t=[];for(var v=0;v<I.length;v++){var H=I[v],S=g.or("TRACK");S.setAttribute("kind","subtitles");S.setAttribute("label",g.uj(H));S.setAttribute("srclang",g.Z5(H));S.setAttribute("id",H.toString());
this.Jh||S.setAttribute("src",this.N.Ky(H,"vtt"));H===F&&S.setAttribute("default","1");t.push(S)}F=this.Z.Oz();F.BR(t);t=F.Qs();this.IF&&this.D3.W(t.textTracks,"change",this.MDY)}else!this.S&&F&&Z0(this,F),this.player.xd("onCaptionsTrackListChanged"),this.player.Zp("onApiChange")};
g.y.MDY=function(){for(var t=this.Z.Oz().Qs().textTracks,F=null,I=0;I<t.length;I++)if(t[I].mode==="showing")a:{F=g.FN(this.N.S,!0);for(var v=0;v<F.length;v++)if(F[v].toString()===t[I].id){F=F[v];break a}F=null}(this.loaded?this.S:null)!==F&&Z0(this,F,!0)};
g.y.VN3=function(){!this.S&&this.C||this.unload()};
g.y.fz=function(t,F,I,v){if(t){var H;ZP_(this,(H=this.S)!=null?H:void 0);this.N.hX()&&(this.pF=[],this.Z.qb("captions"),RU(this.bz),this.KF.reset());a:{H=this.KF;v=v||0;I=chI(H,t,I||0);t=[];try{for(var S=g.l(I),f=S.next();!f.done;f=S.next()){var Q=f.value,R=Q.trackData,n=Q.er,N=H.r0.Y("safari_live_drm_captions_fix");if(typeof R!=="string"){I=t;var M=I.concat;if(N&&wl3(R))var E=P_I(H,R,n);else{var O=H,T=F,W=R,e=n,B=v;if(!YmI(W))throw Error("Invalid binary caption track data");O.N||(O.N=new Px(B,T));
E=O.N.T(W,e)}var p=M.call(I,E)}else{if(R.substring(0,6)==="WEBVTT")var r=t.concat(P_I(H,R,n));else{I=t;var h=I.concat;b:{T=O=void 0;W=H;e=F;if(R[0]==="{")try{W.N||(W.N=new aU(Jhy(e)));var J=T=W.N.T(R,n);break b}catch(tc){g.$B(tc);J=[];break b}var Z=g.Ly(R);if(!Z||!Z.firstChild){var C=Error("Invalid caption track data");C.params=R;throw C;}if(Z.firstChild.tagName==="timedtext"){if(Number(Z.firstChild.getAttribute("format"))===3){W.N||(W.N=new dB(Jhy(e),W.r0));J=O=W.N.T(Z,n);break b}var vi=Error("Unsupported subtitles format in web player (Format2)");
vi.params=R;throw vi;}if(Z.firstChild.tagName==="transcript"){var QT=Error("Unsupported subtitles format in web player (Format1)");QT.params=R;throw QT;}var Hi=Error("Invalid caption track data");Hi.params=R;throw Hi;}r=h.call(I,J)}p=r}t=p}var sK=t;break a}catch(tc){g.dl(H.logger,187101178,"Captions parsing failed: "+tc.message+". ");H.clear();sK=[];break a}sK=void 0}F=sK;F.length>0&&(sK=this.S,this.Rh(sK,!!sK,zA(this)?"g":this.j?"m":"s"));this.player.aK(F,void 0,this.J==="LIVE"||this.J==="SABR_LIVE");
!this.j||this.Jh||zA(this)||g.YG(this.r0)||g.oA(this.r0)||g.hN(this.r0)||this.r0.D3==="shortspage"||this.player.isInline()||(g.He(this.Z3),F=M73({Ij:0,bb:5,Dv:5,Z8:2,textAlign:0,Wv:0,lang:"en"}),this.X4=[F],sK=["Click "," for settings"],this.LF||(S=new g.G0(g.Bt()),g.P(this,S),this.LF=S.element),S=F.end-F.start,(f=g.uj(this.S))&&this.X4.push(new l0(F.start,S,0,F.id,f)),this.X4.push(new l0(F.start,S,0,F.id,sK[0]),new l0(F.start,S,0,F.id,this.LF,!0),new l0(F.start,S,0,F.id,sK[1],!0)),this.player.aK(this.X4),
g.Ij(this.Z3));!this.j||this.Jh||zA(this)||(g.pD(this.r0)?u0(this,!0):Lc(this,!0),this.U&&(this.U.J=this.S),this.player.Le());this.j=!1}};
g.y.onCueRangeEnter=function(t){this.pF.push(t);RU(this.bz)};
g.y.onCueRangeExit=function(t){g.WG(this.pF,t);this.N instanceof s2&&this.N.B&&this.player.hQ([t]);RU(this.bz)};
g.y.getCaptionWindowContainerId=function(){return this.B.element.id};
g.y.Mzh=function(){FWG(this,this.X4);this.X4=null};
g.y.a_=function(){var t=this;if(!this.ea||!this.C){this.bz.stop();g.wip(this.iz);this.pF.sort(g.qI);var F=this.pF;if(this.kP){var I=g.mW(F,function(S){return this.kP.indexOf(S)===-1},this);
I.length&&(F=I)}F=g.l(F);for(I=F.next();!I.done;I=F.next())qm_(this,I.value);F=g.l(Object.entries(this.TY));var v=F.next();for(I={};!v.done;I={pQ:void 0,Bn:void 0},v=F.next()){var H=g.l(v.value);v=H.next().value;H=H.next().value;I.pQ=v;I.Bn=H;this.iz[I.pQ]?(I.Bn.element.parentNode||(I.Bn instanceof JO||I.Bn instanceof AO||g.Iy(this.TY,function(S){return function(f,Q){Q!==S.pQ&&f.S.params.Ij===S.Bn.S.params.Ij&&f.S.params.bb===S.Bn.S.params.bb&&f.S.params.Dv===S.Bn.S.params.Dv&&(f.dispose(),delete t.TY[Q]);
return Q===S.pQ}}(I),this),this.B.element.appendChild(I.Bn.element)),I.Bn.Oc(this.iz[I.pQ])):(I.Bn.dispose(),delete this.TY[I.pQ])}}};
g.y.kju=function(){bPE(this,{},!0);this.player.xd("captionssettingschanged")};
g.y.Lu=function(){var t=D0.IK;t={background:t.background,backgroundOpacity:t.backgroundOpacity,charEdgeStyle:t.charEdgeStyle,color:t.color,fontFamily:t.fontFamily,fontSizeIncrement:t.fontSizeIncrement,fontStyle:t.bold&&t.italic?3:t.bold?1:t.italic?2:0,textOpacity:t.textOpacity,windowColor:D0.windowColor,windowOpacity:D0.windowOpacity};var F=B_I()||{};F.background!=null&&(t.background=F.background);F.backgroundOverride!=null&&(t.backgroundOverride=F.backgroundOverride);F.backgroundOpacity!=null&&(t.backgroundOpacity=
F.backgroundOpacity);F.backgroundOpacityOverride!=null&&(t.backgroundOpacityOverride=F.backgroundOpacityOverride);F.charEdgeStyle!=null&&(t.charEdgeStyle=F.charEdgeStyle);F.charEdgeStyleOverride!=null&&(t.charEdgeStyleOverride=F.charEdgeStyleOverride);F.color!=null&&(t.color=F.color);F.colorOverride!=null&&(t.colorOverride=F.colorOverride);F.fontFamily!=null&&(t.fontFamily=F.fontFamily);F.fontFamilyOverride!=null&&(t.fontFamilyOverride=F.fontFamilyOverride);F.fontSizeIncrement!=null&&(t.fontSizeIncrement=
F.fontSizeIncrement);F.fontSizeIncrementOverride!=null&&(t.fontSizeIncrementOverride=F.fontSizeIncrementOverride);F.fontStyle!=null&&(t.fontStyle=F.fontStyle);F.fontStyleOverride!=null&&(t.fontStyleOverride=F.fontStyleOverride);F.textOpacity!=null&&(t.textOpacity=F.textOpacity);F.textOpacityOverride!=null&&(t.textOpacityOverride=F.textOpacityOverride);F.windowColor!=null&&(t.windowColor=F.windowColor);F.windowColorOverride!=null&&(t.windowColorOverride=F.windowColorOverride);F.windowOpacity!=null&&
(t.windowOpacity=F.windowOpacity);F.windowOpacityOverride!=null&&(t.windowOpacityOverride=F.windowOpacityOverride);return t};
g.y.R_=function(t,F){var I={};Object.assign(I,B_I());Object.assign(I,t);bPE(this,I,F);this.player.xd("captionssettingschanged")};
g.y.Y4=function(){!this.C&&this.loaded&&(g.qF(this.TY,function(t,F){t.dispose();delete this.TY[F]},this),this.a_())};
g.y.Ms=function(t,F){switch(t){case "fontSize":if(isNaN(F))break;t=g.J$(F,-2,4);this.R_({fontSizeIncrement:t});return t;case "reload":F&&!this.C&&Z0(this,this.S,!0);break;case "stickyLoading":F!==void 0&&this.r0.j&&(g.pD(this.r0)?u0(this,!!F):Lc(this,!!F));break;case "track":return tM4(this,F);case "tracklist":return this.N?g.Oi(g.FN(this.N.S,!(!F||!F.includeAsr)),function(I){return g.LD(I)}):[];
case "translationLanguages":return this.N?this.N.C.map(function(I){return Object.assign({},I)}):[];
case "sampleSubtitles":this.C||F===void 0||IBF(this,!!F);break;case "sampleSubtitlesCustomized":this.C||IBF(this,!!F,F);break;case "recommendedTranslationLanguages":return g.eY();case "defaultTranslationSourceTrackIndices":return this.N?this.N.j:[]}};
g.y.getOptions=function(){var t="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.r0.j&&t.push("stickyLoading");return t};
g.y.a5=function(){var t=this.S;if(this.Z.Im("captions")){if(this.r0.Y("html5_modify_caption_vss_logging")){var F;return(t=(F=this.videoData.yG)!=null?F:null)?{cc:g.m4i(t)}:{}}if(t)return F=t.vssId,t.translationLanguage&&F&&(F="t"+F+"."+g.Z5(t)),{cc:F}}return{}};
g.y.cs0=function(){this.isSubtitlesOn()?(g.pD(this.r0)?u0(this,!1):Lc(this,!1),ZP_(this),Z0(this,null,!0)):this.Ju()};
g.y.Ju=function(){var t=zA(this)||!this.S?xN(this,!0):this.S;t&&this.z$(t.vssId,"m");this.isSubtitlesOn()||Z0(this,zA(this)||!this.S?xN(this,!0):this.S,!0)};
g.y.isSubtitlesOn=function(){return!!this.loaded&&!!this.S&&!zA(this)};
g.y.JNz=function(){var t=zA(this);Cc(this,t)?Z0(this,this.getAudioTrack().N,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.hH()&&(this.j=!1,this.S=null,this.N&&(this.N.dispose(),this.N=null)),this.KB()&&(t?Z0(this,xN(this,!1),!1):this.load()))};
g.y.oC=function(t){t&&(this.e7={top:t.top,right:t.right,bottom:t.bottom,left:t.left,width:1-t.left-t.right,height:1-t.top-t.bottom},this.B.element.style.top=this.e7.top*100+"%",this.B.element.style.left=this.e7.left*100+"%",this.B.element.style.width=this.e7.width*100+"%",this.B.element.style.height=this.e7.height*100+"%",this.B.element.style.position="absolute",t=ifI(this))&&(this.B.element.style.width=t.width+"px",this.B.element.style.height=t.height+"px")};
g.y.onVideoDataChange=function(t,F){t==="newdata"&&(this.videoData=F,this.loaded&&this.unload(),this.j=!1,this.S=null,this.N&&(this.N.dispose(),this.N=null,this.player.xd("captionschanged",{})),this.KB()&&this.load())};
g.y.getAudioTrack=function(){return this.player.getAudioTrack()};
g.y.vNF=function(){var t=this.Z.Oz();t&&!t.Et()&&t.E7();this.Z.isFullscreen()?(this.C=this.zY=!0,this.loaded&&this.aW()):(this.zY=this.r0.controlsType==="3",this.C=KrZ(this));Z0(this,this.S)};
g.y.mV=function(){var t,F,I,v=(t=this.videoData.getPlayerResponse())==null?void 0:(F=t.captions)==null?void 0:(I=F.playerCaptionsTracklistRenderer)==null?void 0:I.openTranscriptCommand;v&&this.player.lz("innertubeCommand",v)};
g.y.Rh=function(t,F,I){var v=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,H="";t&&(H=t.vssId,H=H.replace(v,""));var S="";t&&t.getId()&&(S=t.getId()||"");t&&t.getXtags()&&(t=t.getXtags(),t=t.replace(v,""),S=S.concat(";"+t));this.Z.Rh(F?H:"",F?S:"",I)};
g.y.z$=function(t,F){t=(t||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");t.length>0&&this.Z.z$(t,F)};g.YL("captions",C_T);})(_yt_player);
